spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
  redis:
    host: 127.0.0.1
  server:
    port: 9001
